### ISSUE TITLE
pip install of sncosmo fails : release version not compatible with latest astropy

### ISSUE THREAD

**Issue by rbiswas4** [sncosmo/sncosmo#142]
The latest release of SNCosmo seems to be v1.2 released 2015, Dec. This does not seem to be compatible with the latest release of astropy v1.2 (thought it was compatible with the latest release then, and the current development version is).  
```
python
Python 2.7.11 |Anaconda custom (x86_64)| (default, Dec  6 2015, 18:57:58)
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import sncosmo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named sncosmo
>>> exit()
# pip install 
pip install sncosmo
Collecting sncosmo
Collecting astropy (from sncosmo)
  Downloading astropy-1.2.1-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (7.3MB)
    100% |████████████████████████████████| 7.3MB 94kB/s
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/local/software/lib/python2.7/site-packages (from sncosmo)
Requirement already satisfied (use --upgrade to upgrade): scipy in /usr/local/software/lib/python2.7/site-packages (from sncosmo)
Installing collected packages: astropy, sncosmo
Successfully installed astropy-1.2.1 sncosmo-1.2.0

>>> import astropy
>>> import sncosmo
WARNING: AstropyDeprecationWarning: astropy.utils.compat.odict.OrderedDict is now deprecated - import OrderedDict from the collections module instead [astropy.utils.compat.odict]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/software/lib/python2.7/site-packages/sncosmo/__init__.py", line 169, in <module>
    from .builtins import *
  File "/usr/local/software/lib/python2.7/site-packages/sncosmo/builtins.py", line 19, in <module>
    from astropy.config import ConfigurationItem, get_cache_dir
ImportError: cannot import name ConfigurationItem
>>> astropy.__version__
u'1.2.1'
```
This probably happens as the pip requirements file does not specify a maximal version number of astropy that it works with ( > 0.4).

Thanks to @jchiang87 for pointing this out.

Can we have a new release which works with the latest stable version of astropy?

**Comment by kbarbary** [comment]
Yep, I'll try to finish the release tomorrow.

**Comment by rbiswas4** [comment]
Awesome ... Thanks!

**Comment by kbarbary** [comment]
v1.3.0 should be available on pypi now. I've submitted to build the conda package (on the astropy channel) but that is still in progress.
