### PR TITLE
Extending Bandpass Interpolators to Support Non-Radially Variable Telescope Bandpasses

### PR DESCRIPTION
**Pull request by nregnault**
While sncosmo already supports radially variable bandpasses, precision bench and in-situ measurements of effective telescope bandpasses have shown that these variations are not strictly radial. For example, CFHT/MegaCam bandpasses display significant deviations from radial patterns, and ZTF bandpasses exhibit small radial variations, with sensor-to-sensor differences in quantum efficiency (QE) playing a larger role.

In this Merge Request (MR), we introduce several updates:

- **`General Bandpass Interpolator`**: We add a new bandpasses.GeneralBandpassInterpolator class that supports sensor-to-sensor variations as well as general non-radial patterns in bandpasses.

- **`Coordinate Mapping Class`**: A new bandpasses.Transforms class is introduced to map the (x, y, sensor) coordinates of a star to the corresponding focal plane or filter coordinates.

- **Enhanced `get_bandpass` Function**: The bandpasses.get_bandpass function has been updated to optionally use the new interpolator. For standard sncosmo bandpasses, the behavior remains unchanged. However, for bandpasses of the new variable class:
       -  If no coordinates are provided, a static average bandpass (of class Bandpass) is returned.
       -  If coordinates are provided, a 2D array of bandpass transmissions, evaluated on a wavelength grid, is returned.

- **Naming Convention**: We suggest a new naming convention for variable bandpasses: `<instrument>::<bandpass>`, such as `ztf::g` or `megacam6::i2`.

- **New HDF5 Format**: We propose a new HDF5 format to store variable bandpasses, along with functions to map sensors to filters.

### CODE REVIEW

**Comment by benjaminrose** [comment]
Generally, this would need some
- [ ] tests
- [ ] documentation 
- [ ] and fixing the [code style](https://github.com/sncosmo/sncosmo/actions/runs/11366693544/job/31625862223)

I'll look at the implementation in detail next.

**Comment by mmmaat** [comment]
Hi @benjaminrose we fixed what was missing on the PR: we have tests up to a significant coverage, docstrings and expected code style. Are you ready to review it? Thanks.

File: docs/_helpers/bandpass_page.py [hunk 1]
```diff
@@ -26,7 +26,11 @@ def bandpass_table(setname):
     allrefs = []
 
     for m in bandpass_meta:
-        if m['filterset'] != setname:
+        if (
+                m['filterset'] != setname or
+                # special case of ztf position-dependent bandpass
```
Comment (benjaminrose) [inline docs/_helpers/bandpass_page.py:31]: Is there a way to write this to be more generic rather than need to keep a list of all the filter systems with positional-dependent bandpasses?

File: sncosmo/models.py [hunk 2]
```diff
@@ -151,8 +151,10 @@ def _bandflux(model, band, time_or_phase, zp, zpsys):
     for b in set(band):
         mask = band == b
         b = get_bandpass(b)
-
-        fsum = _bandflux_single(model, b, time_or_phase[mask])
+        try:
+            fsum = _bandflux_single(model, b, time_or_phase[mask])
+        except ValueError:
+            continue
```
Comment (benjaminrose) [inline sncosmo/models.py:157]: Why can we just ignore fsum in certain cases? Do we need code in the except block or a comment on why we can ignore fsum in this case?

**Review by benjaminrose — COMMENTED** [review]
Looking good. I had the two questions about the code, but they are simple.

**Comment by benjaminrose** [comment]
I am not sure why I can't rerun the GitHub actions. I can get the tests to pass locally, but I am still working on building the updated documentation.

**Comment by nregnault** [comment]
Sorry I forgot to answer this. It was a leftover from an old patch that should not have been pushed. 
I just reverted it. 

Nicolas. 


De: "Mathieu Bernard" ***@***.***> 
À: "sncosmo/sncosmo" ***@***.***> 
Cc: "Nicolas Regnault" ***@***.***>, "Mention" ***@***.***> 
Envoyé: Mercredi 6 Novembre 2024 23:15:41 
Objet: Re: [sncosmo/sncosmo] Extending Bandpass Interpolators to Support Non-Radially Variable Telescope Bandpasses (PR #400) 






In [ https://github.com/sncosmo/sncosmo/pull/400#discussion_r1831693383 | sncosmo/models.py ] : 
> @@ -151,8 +151,10 @@ def _bandflux(model, band, time_or_phase, zp, zpsys):
     for b in set(band):
         mask = band == b
         b = get_bandpass(b)
-
-        fsum = _bandflux_single(model, b, time_or_phase[mask])
+        try:
+            fsum = _bandflux_single(model, b, time_or_phase[mask])
+        except ValueError:
+            continue 


I let [ https://github.com/nregnault | @nregnault ] react on this, I'm not sure...

File: sncosmo/models.py (hunk 2 above)
Comment (nregnault) [reply sncosmo/models.py]: Apologies, @benjaminrose, I initially replied to this via email but should have responded here.

The issue was a leftover from an old patch that was mistakenly pushed.
I’ve reverted it.

File: setup.cfg
Comment (benjaminrose) [inline setup.cfg:1]: Do we need to add h5py to the `oldestdeps` list of dependancies?

**Review by benjaminrose — COMMENTED** [review]
I think we need to add hdf5 one more list of dependancies. After that, we can either rerun the tests in the PR or merge it and run the tests then.

**Comment by benjaminrose** [comment]
The merge conflicts are simple to resolve, so don't worry about them.

File: setup.cfg
Comment (mmmaat) [reply setup.cfg:1]: Indeed I missed that! This is fixed in [4512ecb](https://github.com/sncosmo/sncosmo/pull/400/commits/4512ecb62a169d77a0d4d0c8d3ead98b2a02661a)

**Comment by benjaminrose** [comment]
I got it working with python3.8. But it look like the builtins are not downloading. Can you check that you are passing/requiring the correct arguments.

https://github.com/sncosmo/sncosmo/actions/runs/12655104392/job/35264622283?pr=400#step:5:73
```
__________________ test_builtin_bandpass_interpolator[ztf::g] __________________

name = 'ztf::g'

    @pytest.mark.might_download
    @pytest.mark.parametrize("name", bandpass_interpolators)
    def test_builtin_bandpass_interpolator(name):
        interpolator = _BANDPASS_INTERPOLATORS.retrieve(name)
>       interpolator.at(interpolator.minpos())
E       TypeError: GeneralBandpassInterpolator.at() missing 2 required positional arguments: 'y' and 'sensor_id'

../lib/python3.12/site-packages/sncosmo/tests/test_download_builtins.py:35: TypeError
```

**Comment by MickaelRigault** [comment]
@nregnault @benjaminrose 
I was wondering where we were concerning this PR ? 

I think I need it for implementing NaCl in skysurvey. 

Do you know ?

**Comment by nregnault** [comment]
Hi Mickael, 

I believe Mathieu has addressed Ben's latest requests, which I’ve now merged. 
Everything should be good on our side. 

Regards, 
Nicolas 



De: "Mickael Rigault" ***@***.***> 
À: "sncosmo/sncosmo" ***@***.***> 
Cc: "Nicolas Regnault" ***@***.***>, "Mention" ***@***.***> 
Envoyé: Jeudi 16 Janvier 2025 18:18:57 
Objet: Re: [sncosmo/sncosmo] Extending Bandpass Interpolators to Support Non-Radially Variable Telescope Bandpasses (PR #400) 





[ https://github.com/nregnault | @nregnault ] [ https://github.com/benjaminrose | @benjaminrose ] 
I was wondering where we were concerning this PR ? 

I think I need it for implementing NaCl in skysurvey. 

Do you know ?

**Comment by benjaminrose** [comment]
Looks good. I'll fix the code style and the merge conflicts, then merge the PR. I can do this by the end of the week.

**Comment by MickaelRigault** [comment]
Amazing !

**Comment by benjaminrose** [comment]
I have merged this PR. You can access it from the master branch, or I will push to PyPI later this week. (I want to add a few smaller PRs before releasing this.)
